version: '2'

services:
  mypercona:
    image: percona:5.6
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "mypercona_data:/var/lib/mysql"
      - "mypercona_logs:/var/log/mysql"
    network_mode: bridge

volumes:
  mypercona_data:
    external: true
  mypercona_logs:
    external: true

